# config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

before_install:
  - echo -e "machine github.com\nlogin $CI_USER_TOKEN" > ~/.netrc


install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy


stages:
  # - test
  # - name: answers
  #  if: branch = master
  - answers

jobs:
  include:
    - stage: test
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script: # code coverage tool
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: pytest --cov-report xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script:
        - pipenv run python3 -m final_project upload https://canvas.harvard.edu/courses/69812/external_tools/22940
